// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI8kuhKYKS8Iy5te2wen44K7Bi8GI-sIs',
    appId: '1:748687696219:web:3309bc64331a398bbbba7e',
    messagingSenderId: '748687696219',
    projectId: 'loginscreen-8b53a',
    authDomain: 'loginscreen-8b53a.firebaseapp.com',
    storageBucket: 'loginscreen-8b53a.firebasestorage.app',
    measurementId: 'G-3BVW97M84P',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMLYVh2h6eQ__0_TWsEIfBw7OKedLAZH8',
    appId: '1:748687696219:ios:180fa02603231b24bbba7e',
    messagingSenderId: '748687696219',
    projectId: 'loginscreen-8b53a',
    storageBucket: 'loginscreen-8b53a.firebasestorage.app',
    iosBundleId: 'com.example.loginScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMLYVh2h6eQ__0_TWsEIfBw7OKedLAZH8',
    appId: '1:748687696219:ios:180fa02603231b24bbba7e',
    messagingSenderId: '748687696219',
    projectId: 'loginscreen-8b53a',
    storageBucket: 'loginscreen-8b53a.firebasestorage.app',
    iosBundleId: 'com.example.loginScreen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI8kuhKYKS8Iy5te2wen44K7Bi8GI-sIs',
    appId: '1:748687696219:web:fa12654a0d5a6fc8bbba7e',
    messagingSenderId: '748687696219',
    projectId: 'loginscreen-8b53a',
    authDomain: 'loginscreen-8b53a.firebaseapp.com',
    storageBucket: 'loginscreen-8b53a.firebasestorage.app',
    measurementId: 'G-RJ76LBF5F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeSd1V09eARrPT-RpqXJoM3e3ttAX_rus',
    appId: '1:748687696219:android:ca2852337764673ebbba7e',
    messagingSenderId: '748687696219',
    projectId: 'loginscreen-8b53a',
    storageBucket: 'loginscreen-8b53a.firebasestorage.app',
  );
}
